-- TuVozApp - Bootstrap minimo para levantar el backend en Supabase
-- Ejecutar una sola vez en el SQL Editor de Supabase.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key,
  full_name text not null,
  role text not null check (
    role in (
      'self',
      'familiar',
      'maestra_integradora',
      'personal_medico',
      'acompanante_terapeutico'
    )
  ),
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  avatar_url text,
  email text,
  auth_user_id uuid,
  owner_user_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  user_id uuid not null references public.users(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  is_owner boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (user_id, profile_id)
);

create index if not exists idx_user_profiles_user on public.user_profiles(user_id);
create index if not exists idx_user_profiles_profile on public.user_profiles(profile_id);

create or replace function public.current_user_linked_to_profile(p_profile_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_profiles up
    where up.profile_id = p_profile_id
      and up.user_id = auth.uid()
  );
$$;

create or replace function public.current_user_owns_profile(p_profile_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_profiles up
    where up.profile_id = p_profile_id
      and up.user_id = auth.uid()
      and up.is_owner = true
  );
$$;

create table if not exists public.profile_settings (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  theme text not null default 'light' check (theme in ('light', 'dark', 'system')),
  uppercase boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  severity text not null default 'info' check (severity in ('info', 'warning', 'error', 'critical')),
  description text not null,
  metadata jsonb,
  source text,
  created_at timestamptz default now()
);

create index if not exists idx_audit_logs_profile on public.audit_logs(profile_id);
create index if not exists idx_audit_logs_event on public.audit_logs(event_type);
create index if not exists idx_audit_logs_created on public.audit_logs(created_at);

create table if not exists public.emergency_profiles (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  full_name text not null,
  blood_type text check (blood_type in ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
  allergies text,
  medications text,
  notes text,
  address text,
  emergency_contact_name text not null,
  emergency_contact_phone text not null,
  alert_type text not null default 'call' check (alert_type in ('call', 'whatsapp_location')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_emergency_profiles_profile on public.emergency_profiles(profile_id);

create table if not exists public.pictograms_categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  image_url text,
  created_at timestamptz default now()
);

create table if not exists public.pictograms (
  id uuid primary key default gen_random_uuid(),
  arasaac_id text not null unique,
  keyword text not null,
  language text not null default 'es',
  category_id uuid not null references public.pictograms_categories(id) on delete restrict,
  last_sync timestamptz,
  created_at timestamptz default now()
);

create index if not exists idx_pictograms_category_id on public.pictograms(category_id);
create index if not exists idx_pictograms_keyword on public.pictograms(keyword);

create table if not exists public.favorite_pictograms (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  pictogram_id uuid not null references public.pictograms(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, pictogram_id)
);

create index if not exists idx_favorite_pictograms_profile on public.favorite_pictograms(profile_id);
create index if not exists idx_favorite_pictograms_pictogram on public.favorite_pictograms(pictogram_id);

create table if not exists public.task_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.routines (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  routine_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint routines_unique_per_day unique (profile_id, routine_date)
);

create index if not exists idx_routines_profile on public.routines(profile_id);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  routine_id bigint not null references public.routines(id) on delete cascade,
  category_id bigint references public.task_categories(id) on delete set null,
  title text not null,
  status text not null default 'Pendiente' check (status in ('Pendiente', 'En Proceso', 'Completado', 'Cancelado')),
  start_time time,
  end_time time,
  reminder timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_tasks_routine_id on public.tasks(routine_id);
create index if not exists idx_tasks_category_id on public.tasks(category_id);

create table if not exists public.task_steps (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  description text,
  step_order integer not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_task_steps_task on public.task_steps(task_id);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  contact_email text,
  subject text not null,
  message text not null,
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Compatibility for existing databases where support_tickets was created
-- before anonymous support flow was introduced.
alter table public.support_tickets
  alter column user_id drop not null;

alter table public.support_tickets
  add column if not exists contact_email text;

create index if not exists idx_support_tickets_user on public.support_tickets(user_id);
create index if not exists idx_support_tickets_contact_email on public.support_tickets(contact_email);

create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  sender text not null check (sender in ('user', 'support')),
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_support_messages_ticket on public.support_messages(ticket_id);

drop trigger if exists trg_profile_settings_updated_at on public.profile_settings;
create trigger trg_profile_settings_updated_at
before update on public.profile_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_emergency_profiles_updated_at on public.emergency_profiles;
create trigger trg_emergency_profiles_updated_at
before update on public.emergency_profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_routines_updated_at on public.routines;
create trigger trg_routines_updated_at
before update on public.routines
for each row execute function public.set_updated_at();

drop trigger if exists trg_tasks_updated_at on public.tasks;
create trigger trg_tasks_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

drop trigger if exists trg_task_steps_updated_at on public.task_steps;
create trigger trg_task_steps_updated_at
before update on public.task_steps
for each row execute function public.set_updated_at();

drop trigger if exists trg_support_tickets_updated_at on public.support_tickets;
create trigger trg_support_tickets_updated_at
before update on public.support_tickets
for each row execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.user_profiles enable row level security;
alter table public.profile_settings enable row level security;
alter table public.audit_logs enable row level security;
alter table public.emergency_profiles enable row level security;
alter table public.pictograms_categories enable row level security;
alter table public.pictograms enable row level security;
alter table public.favorite_pictograms enable row level security;
alter table public.task_categories enable row level security;
alter table public.routines enable row level security;
alter table public.tasks enable row level security;
alter table public.task_steps enable row level security;
alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;

drop policy if exists users_select_own on public.users;
drop policy if exists users_insert_own on public.users;
drop policy if exists users_update_own on public.users;

create policy users_select_own on public.users
for select to authenticated
using (id = auth.uid());

create policy users_insert_own on public.users
for insert to authenticated
with check (id = auth.uid());

create policy users_update_own on public.users
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists profiles_select_linked on public.profiles;
drop policy if exists profiles_insert_authenticated on public.profiles;
drop policy if exists profiles_update_linked on public.profiles;
drop policy if exists profiles_delete_linked on public.profiles;

create policy profiles_select_linked on public.profiles
for select to authenticated
using (
  owner_user_id = auth.uid()
  or auth_user_id = auth.uid()
  or public.current_user_linked_to_profile(id)
);

create policy profiles_insert_authenticated on public.profiles
for insert to authenticated
with check (true);

create policy profiles_update_linked on public.profiles
for update to authenticated
using (
  owner_user_id = auth.uid()
  or auth_user_id = auth.uid()
  or public.current_user_linked_to_profile(id)
)
with check (
  owner_user_id = auth.uid()
  or auth_user_id = auth.uid()
  or public.current_user_linked_to_profile(id)
);

create policy profiles_delete_linked on public.profiles
for delete to authenticated
using (
  owner_user_id = auth.uid()
  or auth_user_id = auth.uid()
  or public.current_user_linked_to_profile(id)
);

drop policy if exists user_profiles_select_linked on public.user_profiles;
drop policy if exists user_profiles_insert_linked on public.user_profiles;
drop policy if exists user_profiles_update_linked on public.user_profiles;
drop policy if exists user_profiles_delete_linked on public.user_profiles;

create policy user_profiles_select_linked on public.user_profiles
for select to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1
    from public.user_profiles up
    where up.profile_id = user_profiles.profile_id
      and up.user_id = auth.uid()
  )
);

create policy user_profiles_insert_linked on public.user_profiles
for insert to authenticated
with check (
  user_id = auth.uid()
  or public.current_user_owns_profile(profile_id)
);

create policy user_profiles_update_linked on public.user_profiles
for update to authenticated
using (
  user_id = auth.uid()
  or public.current_user_owns_profile(profile_id)
)
with check (
  user_id = auth.uid()
  or public.current_user_owns_profile(profile_id)
);

create policy user_profiles_delete_linked on public.user_profiles
for delete to authenticated
using (
  user_id = auth.uid()
  or public.current_user_owns_profile(profile_id)
);

drop policy if exists profile_settings_select_linked on public.profile_settings;
drop policy if exists profile_settings_insert_linked on public.profile_settings;
drop policy if exists profile_settings_update_linked on public.profile_settings;
drop policy if exists profile_settings_delete_linked on public.profile_settings;

create policy profile_settings_select_linked on public.profile_settings
for select to authenticated
using (public.current_user_linked_to_profile(profile_id));

create policy profile_settings_insert_linked on public.profile_settings
for insert to authenticated
with check (public.current_user_linked_to_profile(profile_id));

create policy profile_settings_update_linked on public.profile_settings
for update to authenticated
using (public.current_user_linked_to_profile(profile_id))
with check (public.current_user_linked_to_profile(profile_id));

create policy profile_settings_delete_linked on public.profile_settings
for delete to authenticated
using (public.current_user_linked_to_profile(profile_id));

drop policy if exists audit_logs_select_own on public.audit_logs;
drop policy if exists audit_logs_insert_own on public.audit_logs;

create policy audit_logs_select_own on public.audit_logs
for select to authenticated
using (
  profile_id is null
  or public.current_user_linked_to_profile(profile_id)
);

create policy audit_logs_insert_own on public.audit_logs
for insert to authenticated
with check (
  profile_id is null
  or public.current_user_linked_to_profile(profile_id)
);

drop policy if exists emergency_profiles_select_own on public.emergency_profiles;
drop policy if exists emergency_profiles_insert_own on public.emergency_profiles;
drop policy if exists emergency_profiles_update_own on public.emergency_profiles;
drop policy if exists emergency_profiles_delete_own on public.emergency_profiles;

create policy emergency_profiles_select_own on public.emergency_profiles
for select to authenticated
using (public.current_user_owns_profile(profile_id));

create policy emergency_profiles_insert_own on public.emergency_profiles
for insert to authenticated
with check (public.current_user_owns_profile(profile_id));

create policy emergency_profiles_update_own on public.emergency_profiles
for update to authenticated
using (public.current_user_owns_profile(profile_id))
with check (public.current_user_owns_profile(profile_id));

create policy emergency_profiles_delete_own on public.emergency_profiles
for delete to authenticated
using (public.current_user_owns_profile(profile_id));

drop policy if exists pictograms_categories_read_all on public.pictograms_categories;
create policy pictograms_categories_read_all on public.pictograms_categories
for select to authenticated
using (true);

drop policy if exists pictograms_read_all on public.pictograms;
create policy pictograms_read_all on public.pictograms
for select to authenticated
using (true);

drop policy if exists favorite_pictograms_select_linked on public.favorite_pictograms;
drop policy if exists favorite_pictograms_insert_linked on public.favorite_pictograms;
drop policy if exists favorite_pictograms_delete_linked on public.favorite_pictograms;

create policy favorite_pictograms_select_linked on public.favorite_pictograms
for select to authenticated
using (
  exists (
    select 1
    from public.user_profiles up
    where up.profile_id = favorite_pictograms.profile_id
      and up.user_id = auth.uid()
  )
);

create policy favorite_pictograms_insert_linked on public.favorite_pictograms
for insert to authenticated
with check (
  exists (
    select 1
    from public.user_profiles up
    where up.profile_id = favorite_pictograms.profile_id
      and up.user_id = auth.uid()
  )
);

create policy favorite_pictograms_delete_linked on public.favorite_pictograms
for delete to authenticated
using (
  exists (
    select 1
    from public.user_profiles up
    where up.profile_id = favorite_pictograms.profile_id
      and up.user_id = auth.uid()
  )
);

drop policy if exists task_categories_read_all on public.task_categories;
create policy task_categories_read_all on public.task_categories
for select to authenticated
using (true);

drop policy if exists routines_select_linked on public.routines;
drop policy if exists routines_insert_linked on public.routines;
drop policy if exists routines_update_linked on public.routines;
drop policy if exists routines_delete_linked on public.routines;

create policy routines_select_linked on public.routines
for select to authenticated
using (public.current_user_linked_to_profile(profile_id));

create policy routines_insert_linked on public.routines
for insert to authenticated
with check (public.current_user_linked_to_profile(profile_id));

create policy routines_update_linked on public.routines
for update to authenticated
using (public.current_user_linked_to_profile(profile_id))
with check (public.current_user_linked_to_profile(profile_id));

create policy routines_delete_linked on public.routines
for delete to authenticated
using (public.current_user_linked_to_profile(profile_id));

drop policy if exists tasks_select_linked on public.tasks;
drop policy if exists tasks_insert_linked on public.tasks;
drop policy if exists tasks_update_linked on public.tasks;
drop policy if exists tasks_delete_linked on public.tasks;

create policy tasks_select_linked on public.tasks
for select to authenticated
using (
  exists (
    select 1
    from public.routines r
    where r.id = tasks.routine_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
);

create policy tasks_insert_linked on public.tasks
for insert to authenticated
with check (
  exists (
    select 1
    from public.routines r
    where r.id = tasks.routine_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
);

create policy tasks_update_linked on public.tasks
for update to authenticated
using (
  exists (
    select 1
    from public.routines r
    where r.id = tasks.routine_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
)
with check (
  exists (
    select 1
    from public.routines r
    where r.id = tasks.routine_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
);

create policy tasks_delete_linked on public.tasks
for delete to authenticated
using (
  exists (
    select 1
    from public.routines r
    where r.id = tasks.routine_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
);

drop policy if exists task_steps_select_linked on public.task_steps;
drop policy if exists task_steps_insert_linked on public.task_steps;
drop policy if exists task_steps_update_linked on public.task_steps;
drop policy if exists task_steps_delete_linked on public.task_steps;

create policy task_steps_select_linked on public.task_steps
for select to authenticated
using (
  exists (
    select 1
    from public.tasks t
    join public.routines r on r.id = t.routine_id
    where t.id = task_steps.task_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
);

create policy task_steps_insert_linked on public.task_steps
for insert to authenticated
with check (
  exists (
    select 1
    from public.tasks t
    join public.routines r on r.id = t.routine_id
    where t.id = task_steps.task_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
);

create policy task_steps_update_linked on public.task_steps
for update to authenticated
using (
  exists (
    select 1
    from public.tasks t
    join public.routines r on r.id = t.routine_id
    where t.id = task_steps.task_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
)
with check (
  exists (
    select 1
    from public.tasks t
    join public.routines r on r.id = t.routine_id
    where t.id = task_steps.task_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
);

create policy task_steps_delete_linked on public.task_steps
for delete to authenticated
using (
  exists (
    select 1
    from public.tasks t
    join public.routines r on r.id = t.routine_id
    where t.id = task_steps.task_id
      and public.current_user_linked_to_profile(r.profile_id)
  )
);

drop policy if exists support_tickets_select_own on public.support_tickets;
drop policy if exists support_tickets_insert_own on public.support_tickets;
drop policy if exists support_tickets_insert_public on public.support_tickets;
drop policy if exists support_tickets_update_own on public.support_tickets;

create policy support_tickets_select_own on public.support_tickets
for select to authenticated
using (user_id = auth.uid());

create policy support_tickets_insert_own on public.support_tickets
for insert to authenticated
with check (user_id = auth.uid());

create policy support_tickets_insert_public on public.support_tickets
for insert to anon, authenticated
with check (
  user_id is null
  and contact_email is not null
  and length(trim(contact_email)) > 0
);

create policy support_tickets_update_own on public.support_tickets
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists support_messages_select_own on public.support_messages;
drop policy if exists support_messages_insert_own on public.support_messages;

create policy support_messages_select_own on public.support_messages
for select to authenticated
using (
  exists (
    select 1
    from public.support_tickets st
    where st.id = support_messages.ticket_id
      and st.user_id = auth.uid()
  )
);

create policy support_messages_insert_own on public.support_messages
for insert to authenticated
with check (
  exists (
    select 1
    from public.support_tickets st
    where st.id = support_messages.ticket_id
      and st.user_id = auth.uid()
  )
);

create or replace function public.create_user_with_profile(
  p_id uuid,
  p_email text,
  p_full_name text,
  p_role text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
begin
  if auth.uid() is distinct from p_id then
    raise exception 'Authenticated user does not match p_id';
  end if;

  insert into public.users (id, full_name, role, email)
  values (p_id, p_full_name, p_role, lower(trim(p_email)))
  on conflict (id) do update set
    full_name = excluded.full_name,
    role = excluded.role,
    email = excluded.email;

  select up.profile_id
  into v_profile_id
  from public.user_profiles up
  where up.user_id = p_id
    and up.is_owner = true
  limit 1;

  if v_profile_id is null then
    insert into public.profiles (display_name, avatar_url, email, auth_user_id, owner_user_id)
    values (p_full_name, null, lower(trim(p_email)), p_id, p_id)
    returning id into v_profile_id;

    insert into public.user_profiles (user_id, profile_id, is_owner)
    values (p_id, v_profile_id, true)
    on conflict (user_id, profile_id) do update set is_owner = excluded.is_owner;

    insert into public.profile_settings (profile_id)
    values (v_profile_id)
    on conflict (profile_id) do nothing;
  else
    update public.profiles
    set display_name = p_full_name,
        email = lower(trim(p_email)),
        auth_user_id = coalesce(auth_user_id, p_id),
        owner_user_id = coalesce(owner_user_id, p_id)
    where id = v_profile_id;

    insert into public.profile_settings (profile_id)
    values (v_profile_id)
    on conflict (profile_id) do nothing;
  end if;

  return jsonb_build_object(
    'success', true,
    'user_id', p_id,
    'profile_id', v_profile_id
  );
end;
$$;

grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to authenticated, service_role;
grant insert on table public.support_tickets to anon;
grant all on all sequences in schema public to authenticated, service_role;
grant execute on all functions in schema public to authenticated, service_role;

insert into storage.buckets (id, name, public)
values
  ('Avatar', 'Avatar', true),
  ('Categorias', 'Categorias', true)
on conflict (id) do update set public = excluded.public;

-- ============================================================
-- Storage RLS policies para el bucket Avatar
-- Los usuarios autenticados solo pueden operar sobre su propia
-- carpeta ({profile_id}/...). La lectura es pública (bucket público).
-- ============================================================
drop policy if exists avatar_insert on storage.objects;
drop policy if exists avatar_update on storage.objects;
drop policy if exists avatar_delete on storage.objects;
drop policy if exists avatar_select on storage.objects;

create policy avatar_select on storage.objects
  for select
  using (bucket_id = 'Avatar');

create policy avatar_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'Avatar'
    and (storage.foldername(name))[1] in (
      select p.id::text
      from public.user_profiles up
      join public.profiles p on p.id = up.profile_id
      where up.user_id = auth.uid()
    )
  );

create policy avatar_update on storage.objects
  for update to authenticated
  using (
    bucket_id = 'Avatar'
    and (storage.foldername(name))[1] in (
      select p.id::text
      from public.user_profiles up
      join public.profiles p on p.id = up.profile_id
      where up.user_id = auth.uid()
    )
  );

create policy avatar_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'Avatar'
    and (storage.foldername(name))[1] in (
      select p.id::text
      from public.user_profiles up
      join public.profiles p on p.id = up.profile_id
      where up.user_id = auth.uid()
    )
  );

-- ============================================================
-- MIGRACIÓN: renombrar profiles.full_name → profiles.display_name
-- Ejecutar una sola vez sobre bases de datos existentes.
-- ============================================================
alter table public.profiles
  rename column full_name to display_name;
